//weather
export const FETCH_WEATHER = 'FETCH_WEATHER';
export const FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS';
export const FETCH_WEATHER_ERROR = 'FETCH_WEATHER_ERROR';

//climate
export const FETCH_CLIMATE = 'FETCH_CLIMATE';
export const FETCH_CLIMATE_SUCCESS = 'FETCH_CLIMATE_SUCCESS';
export const FETCH_CLIMATE_ERROR = 'FETCH_CLIMATE_ERROR';

//authentication
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
export const FORGOTPASSWORD = 'FORGOTPASSWORD';
export const SIGNUP = 'SIGNUP';
